### ISSUE TITLE
Support for relationships

### ISSUE THREAD

**Issue by Glavin001** [feathersjs/feathers-mongoose#1]
See Populate: http://mongoosejs.com/docs/populate.html 
Another example: http://stackoverflow.com/a/11920421/2578205

**Comment by purpleP** [comment]
So... Any development on that?

**Comment by ekryski** [comment]
@purpleP once PR #18 lands you will be able to use `$populate`. We also have a [feathers-associations](https://github.com/feathersjs/feathers-associations) plugin. It still needs a bit of polish but that will probably be wrapped up in the next week or two as well.
