### ISSUE TITLE
How to change response code and data

### ISSUE THREAD

**Issue by supasate** [feathersjs/feathers-mongoose#102]
I would like my API to return `404 Not Found` when a requested data does not exist. Currently, it responds with `400 Bad Request`. How can I intercept and modify the response?

**Example**
Request: `GET localhost/mymodels/1234`
Response header: `400 Bad Request`
Response Data: `{"name":"BadRequest","message":"Cast to ObjectId failed for value \"1234\" at path \"_id\"","code":400,"className":"bad-request","errors":{}}`

I would like to change the response to something like this:

> Response header: `404 Not Found`
> Response data: `{"name":"NotFound","message":"Requested ID does not exist","code":404,"className":"not-found","errors":{}}`

or just

> Response Header: `404 Not Found`
> Response data: `{"name":"NotFound","message":"Requested ID does not exist","code":404}`

**Comment by marshallswain** [comment]
Can you try throwing an error using one of the feathers-errors?

**Comment by supasate** [comment]
I'm not quite sure where should I throw the error. Please advise.

Here's my code.

``` javascript
const service = require('feathers-mongoose');

module.exports = function() {
  const app = this;
  const options = {
    Model: mymodels,
    paginate: {
      default: 5,
      max: 50
    }
  };
  app.use('/mymodels', service(options));
}
```

**Comment by daffl** [comment]
Not having a 404 here should definitely be fixed in the adapter. To further customize the errors I am thinking of adding `afterError` hooks but for now you can probably [extend the adapter](http://docs.feathersjs.com/databases/extending.html) and throw your own errors.

**Comment by supasate** [comment]
I found the root cause is caused by using [Mongoose findOne with id](https://github.com/feathersjs/feathers-mongoose/blob/fd64ac42121fae3df496c3787f95f8bf4bf36704/src/service.js#L97-L100). So, when a requested id is not in the proper ObjectId format, Mongoose throws `CastError`.

Should we fix it by first checking the format? If it's not in ObjectId format, we throw ``new errors.NotFound(`No record found for id '${id}'`)`` instead. 

If you think it's ok to fix this way, I would like to try to send a PR to fix it.

**Comment by supasate** [comment]
@daffl I created a PR on this issue. I'm new to this community. Please advise.

**Comment by ekryski** [comment]
I don't think this should actually throw a 404, because if it is a bad ID (which it is) then it actually is a bad request. If you want to have a 404 you can easily add your own `before` hook to quickly check if `hook.id` is a valid ObjectId.

**Comment by ekryski** [comment]
The other thing is we currently support having an alternative id fields as the primary instead of the default `_id` so we can't just throw a 404 on any id that isn't an ObjectId. For example, you could be using something like `email` as your primary id to query by.

**Comment by daffl** [comment]
For the hook implementation for this case see https://github.com/feathersjs/feathers-mongoose/pull/103#issuecomment-233206434

**Comment by supasate** [comment]
@ekryski @daffl I agree. I totally forgot about alternative id. Thank you for your clarification and help.
