### ISSUE TITLE
Soft Delete

### ISSUE THREAD

**Issue by jeremyjs** [feathersjs/feathers-mongoose#109]
It would be nice to have a built in soft-delete.

Here is some inspiration: https://github.com/dsanel/mongoose-delete

Ideally, you would be able to pass in options:

```
app.use('messages', service({,
  Model: Message,
  paginate: {
    default: 2,
    max: 4
  },
  softDelete: {
    fieldName: 'isDeleted',
    deletedBy: true
  }
}));
```

Example service usage:

```
app.service('/messages').remove(null, { query: { text: 'foo' }, deletedBy: myUserId });
```

**Comment by marshallswain** [comment]
Hey @jeremyjs.  This is something that you would want to implement as a hook.  It's actually way simple to implement:  https://github.com/feathersjs/feathers-mongoose/issues/76#issuecomment-210863012

I think it wouldn't hurt to have a bundled hook for this that allows for passing the options you specified, though.  Actually, it would be handy.

```js
import softDelete from 'feathers-mongoose/hooks/soft-delete';
app.service('/v1/messages').before({
   remove: [
      softDelete({
         fieldName: 'isDeleted',
         deletedBy: true
      })
   ]
});
```

**Comment by marshallswain** [comment]
Actually, it would be more useful as a general hook, not just a feathers-mongoose hook.

**Comment by daffl** [comment]
A soft delete hook is already documented as an example at http://docs.feathersjs.com/hooks/examples.html

**Comment by ekryski** [comment]
Closing as I think there are some good solutions here. Hopefully that helped you @jeremyjs! 😄

**Comment by daffl** [comment]
Might be worth investigating if we want to add it as a bundled hook at one point.

**Comment by ekryski** [comment]
ya maybe. I have quite a few good hooks now that we should shove into the common repo.

**Comment by cklmercer** [comment]
The soft-delete example is no longer available, or at least the link here and the one in the docs are both resulting in a 404 error.

**Comment by eddyystop** [comment]
A new softDelete hooks has been written for Auk https://docs.feathersjs.com/v/auk/hooks/common/database.html

Perhaps that handles your needs.

**Comment by elixiao** [comment]
Page Not found for url : [https://docs.feathersjs.com/v/auk/hooks/common/database.html](https://docs.feathersjs.com/v/auk/hooks/common/database.html)

**Comment by daffl** [comment]
It is all available at the main documentation at https://docs.feathersjs.com/, specifically https://docs.feathersjs.com/api/hooks-common.html#softdelete

**Comment by prashantnirgun** [comment]
This also is broken link
