### ISSUE TITLE
Add changelog binary to repo

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-mongoose#114]
Currently publishing blows up if you don't have the binary installed. At a minimum we should add a `postinstall` task to install the binary, however I'd prefer to have it in a `bin/` directory.

**Comment by daffl** [comment]
It's a Ruby gem. We could run add a pre publish script that checks if it is installed.

**Comment by ekryski** [comment]
Closing this issue. This is being tracked across all repos here: https://github.com/feathersjs/feathers/issues/433
