### ISSUE TITLE
Mongoose ValidationError messages do not surface

### ISSUE THREAD

**Issue by jonjamz** [feathersjs/feathers-mongoose#116]
I tried creating a user with an invalid field and the service gave me a FeathersError:

`BadRequest: user validation failed`

However, creating that user with the same invalid data using the Mongoose model directly yielded much more useful error messaging:

`'avatar.files.img': { /avatar-placeholder.gif is not a valid URL! ...`

Is there something specific that I can do to get these validation messages without having to manually use the model each time I encounter such an error?

**Comment by daffl** [comment]
You are not getting any additional information in the `errors` or `data` property?

**Comment by kaiquewdev** [comment]
@jonjamz Do you have some samples about this specific issue who you can share with us to help you?

**Comment by ekryski** [comment]
@jonjamz what did you want to see? Are you referring to having more information in the server logs? The error details are there in the error object and get sent back to the client over JSON but we would likely need to update the feathers error handler to just spit out the attributes.

Either that or register your own error handler.

**Comment by jonjamz** [comment]
@ekryski yes it sounds like an update to the feathers error handler would do the trick. I would like to see whatever messaging is in the original error logged also on the server, as if it was never wrapped in anything else. This would make for a much nicer developer experience I think.

**Comment by jonjamz** [comment]
@daffl I didn't check those properties at the time, but looking at the error handler code for this library it seems like all that information should be there in the error object. It would just be nice to see it on the server without any extra work.

**Comment by ekryski** [comment]
I think this is resolved. This is a pretty old issue and we have been seeing validation errors in production apps for quite a while.

Closing. Please re-open if this is still relevant.
