### ISSUE TITLE
$or query with a REST GET request ($or needs an array)

### ISSUE THREAD

**Issue by sylvainlap** [feathersjs/feathers-mongoose#117]
Hi,

With REST provider & mongoose, I can easily query with $in, $sort... like that:
`GET /messages?read=true&$sort[createdAt]=-1`

The result query will be
```
{
  "read": "true",
  "$sort": { "createdAt": "-1" }
}
```

But how can I do a $or query with the REST provider ? because
`GET /users?$or[roles]=admin&$or[roles]=super-admin`

will result as:
```
{
  "$or": {
    roles: [admin, super-admin]
  }
}
```

However, $or needs an array. How can I build my GET query request to get the expected format http://docs.feathersjs.com/databases/querying.html#or ?

**Comment by daffl** [comment]
The query is parsed with Nodes [querystring](https://nodejs.org/api/querystring.html) module which should show some examples for how to do arrays.

Your query looks more like a candidate for [$in](http://docs.feathersjs.com/databases/querying.html) though I think: `GET /users?roles[$in]=admin&roles[$in]=super-admin`

**Comment by sylvainlap** [comment]
The $in solution works, thanks !

However, I did not find in querystring docs how to do array. So I can manage to create a $or request with a GET REST call.

**Comment by daffl** [comment]
I think you are right, nested objects don't seem to be possible with the built-in module. You should be able to replace it with [qs](https://github.com/ljharb/qs) which is able to do more advanced parsing.

**Comment by sylvainlap** [comment]
OK, thanks for your answers !
