### ISSUE TITLE
$populate across multiple levels

### ISSUE THREAD

**Issue by mcnamee** [feathersjs/feathers-mongoose#119]
Hi,
Is it currently possible to populate [across multiple levels](http://mongoosejs.com/docs/populate.html#populate_multiple_documents) via a rest URL get request?

For example, populating the friends array with user data:

```
const userSchema = new Schema({
   name: { type: String, default: '', required: true },
   friends: [
      { friendId: { type: String, ref: 'users' },
...
```

If not, any advice on how this could be achieved?

**Comment by adamh114** [comment]
Assuming the `users` schema/model is registered, this works for me. 

`/service-name/?$populate[]=friends.friendId`

I'll add that I've only done this when the field to populate is `{type: Schema.Types.ObjectId},` so I'm not sure if it'll work with type `String` or not.

**Comment by mcnamee** [comment]
Ah ha, I didn't realise you could do square brackets deal. Thanks so much @adamh114

**Comment by designalchemy** [comment]
> Assuming the `users` schema/model is registered, this works for me.
> 
> `/service-name/?$populate[]=friends.friendId`
> 
> I'll add that I've only done this when the field to populate is `{type: Schema.Types.ObjectId},` so I'm not sure if it'll work with type `String` or not.

@adamh114 
Is this still working
