### ISSUE TITLE
Allow overriding default CRUD methods

### ISSUE THREAD

**Issue by agonbina** [feathersjs/feathers-mongoose#12]
There might be a time when there is a need to override one of the methods. I'm thinking: 
```
mongooseService(modelName, schema, {
  find: function(...) {
    // override default logic
  }
}, mongoose);
```

Of course we can just override the method directly but if it's passed in as an option we could avoid setting the default on Store

**Comment by ekryski** [comment]
Once PR #18 lands you'll be able to extend services explicitly or use hooks. [feathers-hooks](https://github.com/feathersjs/feathers-hooks) has a bunch of documentation on how they can be used, and we also have a more comprehensive guide on [using hooks for validation](http://feathersjs.com/learn/validation/).
