### ISSUE TITLE
Query filter does not work with booleans

### ISSUE THREAD

**Issue by sylvainlap** [feathersjs/feathers-mongoose#122]
Hi,

I have a model with a boolean, for example `blogpost.published`.

If I query GET /blogposts?published=true, I got nothing because `published` in the query sent to mongoose is a String, with "true", instead of being a Boolean `true`.

How can I query booleans ?

**Comment by jamesjnadeau** [comment]
@sylvainlap can you please try using a truthy number, like 1 instead of the string true? I think that should work.

**Comment by sylvainlap** [comment]
yeah that works, thanks.

**Comment by daffl** [comment]
Another option is to convert the query values in a hook:

```js
app.service('myservice').before({
  find(hook) {
    const query = hook.params.query;

    if(query.published !== undefined) {
      hook.params.query.published = query.published === 'true' ? true : false;
    }
  }
});
```

**Comment by ekryski** [comment]
@feathersjs/core-team that might be a good common hook. Convert querystring booleans as strings to actual booleans, or possibly something that feathers-commons or core should do.

**Comment by eddyystop** [comment]
I tagged this as a todo for myself.
