### ISSUE TITLE
Add MongoDB requirement information to README

### ISSUE THREAD

**Issue by NetOperatorWibby** [feathersjs/feathers-mongoose#128]
^

**Comment by jamesjnadeau** [comment]
I'm confused by your request @NetOperatorWibby? What do you think should be added to the README?

From my perspective, mongoose is a MongoDB ORM, so it's second nature to me that it would require MongoDB? 

Can you help me better understand your confusion so we can make changes that might help others?

**Comment by NetOperatorWibby** [comment]
I didn't know I had to install MongoDB to use mongoose and I figured other people might have the same confusion.
