### ISSUE TITLE
How do I get average?

### ISSUE THREAD

**Issue by evgenyboxer** [feathersjs/feathers-mongoose#140]
Hey,

I'm trying to figure out how to calculate the average rating for a review.
my review model has a rating field, its an array of objects that looks like:
```
rating: [ { communication: 5, value: 4, accuracy: 5 }, ... ] 
```
How do I calculate the average of communication/value/accuracy using feathers-mongoose?

Here's my solution not using mongoose (Its in the after hooks)
```
(hook, next) => {
   const data = hook.result.data;
    hook.result.avg.communication = mean(data.map(entry => entry.rating.communication));
    ...
```

**Comment by daffl** [comment]
The hook solution looks fine to me (definitely easier than trying to figure out the right MongoDB query for this, it is database agnostic and probably not any slower). As long as you make sure the Mongoose model gets converted to an object before modifying the result I don't see a problem with this.
