### ISSUE TITLE
Update examples for 1.0.0 and add example for extension

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-mongoose#15]
I think some of the examples need to be updated to get ready for version 1.0.0 and an example for extending a Mongoose service with hooks (I [added one to feathers-mongodb](https://github.com/feathersjs/feathers-mongodb/blob/master/README.md)) would be nice.

**Comment by aturkelson** [comment]
Any update on this?  I'd really love to be able to use an official version compatible with the latest feathers release.

**Comment by ekryski** [comment]
Apologies! I have been slammed with work. I'll have something out by the end of the weekend.

**Comment by ekryski** [comment]
Wow! This is embarrassing....

PR is imminent.

**Comment by daffl** [comment]
I think we should just remove all the peer dependencies in all plugins.

**Comment by ekryski** [comment]
@daffl yup the peer dep is gone. Currently we still have `feathers` as a dev dependency for examples and for access to `feathers-errors`.  We don't declare `feathers` as a dep even though we actually do depend on it.

Personally I would prefer to explicitly just declare `feathers-errors` as a dependency in all db adapters, and have `feathers` as a dev dependency. But realistically you probably wouldn't use these adapters without feathers in the first place, so it's probably not  a huge deal.

**Comment by daffl** [comment]
Yeah, I think that should be the plan. They should still work. How does it pull Feathers in? DB adapters should ideally work standalone eventually.

**Comment by ekryski** [comment]
See https://github.com/feathersjs/feathers-mongoose/blob/pre-release/lib/feathers-mongoose.js#L4

So it would just bomb whenever you tried to run the adapter code without feathers installed.

**Comment by daffl** [comment]
Good point then, we should probably just make it dependent on feathers-errors but its good for now.
