### ISSUE TITLE
using lean options in a service with a subdocument model doesn't seem to work 

### ISSUE THREAD

**Issue by quentin-sommer** [feathersjs/feathers-mongoose#157]
### Steps to reproduce
When setting lean at true on service creation the subdocuments still seem to be mongoose object, am I missing something or is this intended behavior ?

### Expected behavior
``` javascript
const Schema = require('mongoose') = mongoose.Schema
const barSchema = new Schema({
data: {type: Number, default: 0}
})

const schema = new Schema({
   foo: {type: barSchema}
})
```
Using `lean: true` on service().
query result should be an object with a foo object
### Actual behavior
Logging Object.keys(result.foo) outputs:
```
['$isSingleNested',
  '$__',
  'isNew',
  'errors',
  '_doc',
  '$__original_save',
  'save',
  '_pres',
  '_posts',
  '$__original_validate',
  'validate',
  '$__original_remove',
  'remove',
  '$parent' ]
```

### System configuration
**Module versions** (especially the part that's not working):

 feathers-mongoose version 3.5.3

**NodeJS version**:

7.4.0

**Operating System**:

Linux

**Comment by jamesjnadeau** [comment]
Hi @quentin-sommer, can you please show your service creation, I think that's where the confusion lies, that's the point where you set the lean option. Should look something like this:

```
var service = feathersMongoose({
  Model: model,
  lean: true,
});
```

**Comment by quentin-sommer** [comment]
Hi, thanks for replying so quickly!

I'm creating the service exactly this way:

``` javascript
const options = {
    Model: schema,
    lean: true,
  }
feathersMongoose(options)
```

**Comment by quentin-sommer** [comment]
Found the problem, query was coming from a direct mongoose call (service.Model.findById()) that is not controlled by feathers!

**Comment by jamesjnadeau** [comment]
@quentin-sommer  I've done that before ;)
