### ISSUE TITLE
Make sure create many works with lean:true.  Follow up on #160

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-mongoose#161]
Follow up work after https://github.com/feathersjs/feathers-mongoose/pull/160

We need to make sure create is returning the correct type of object whether lean is on or off.  @daffl ran into an issue with this.

**Comment by ekryski** [comment]
@marshallswain what was the issue? Is this still relevant?

**Comment by daffl** [comment]
Yes. Something like

```js
mongooseService.create([{
  name: 'David'
}, {
  name: 'Eric'
}, {
  name: 'Marshall'
}]);
```

Might still return Mongoose models (haven't tested it though).
