### ISSUE TITLE
How can I pass additional query parameters in a REST `put` operation?

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [feathersjs/feathers-mongoose#162]
I would like to update an item inside a document's array via [positional operator `$`](https://docs.mongodb.com/manual/reference/operator/update/positional/#update-documents-in-an-array) of Mongoose/MongoDB query, and thus need to not only pass ID of an updated document but also an additional query for array objects. Despite all attempts Mongoose says that "The positional operator did not find the match needed from the query. Unexpanded update: faculcies.$.name".

I call 'PUT' on URL like /univercities/{docID}?faculcies._id={faculcyID} via fetch:

```
fetch(`/univercities/${this.parent.univercity._id}?faculcies._id=${this.faculcy._id}`, {
    method: 'put',
    body:  JSON.stringify({
        '$set': {
            'faculcies.$.name': this.faculcy.name
        }
    }),
    headers: {
        Accept: 'application/json',
        'Content-Type': 'application/json',
        Authorization: sessionStorage.accessToken
    }
})
.then( … )
```

The `hook.params.query` becomes `{ 'faculcies._id': '589d3fc48fe3632ed854beee' }`, but this additional query seems to be ignored. All IDs are valid and there are no spelling mistakes. 
It is also impossible to 'PUT' something on `/univercities?_id={univercityID}&faculcies._id={faculcyID}`.

Am I missing something? Or is it something just not implemented?

**Comment by marshallswain** [comment]
@CosmoMyzrailGorynych I haven't tried that, yet.  Can you set a breakpoint in feathers-mongoose and verify that the data is getting passed in properly?

**Comment by daffl** [comment]
From what I understand, `faculcies` is an array but `faculcies._id` will try to query for `{ faculcies: { _id } }`. You will have to use the [$elemMatch selector](https://docs.mongodb.com/manual/reference/operator/query/elemMatch/) to find items in an array.

**Comment by DominikTrenz** [comment]
I can't get it working neither. I tried this:
`userService.update({
    "_id":"mainDocumentID",  
    "subdocs":
    {$elemMatch: {_id: "someId"}}
}, {
    $set:{
      "subdocs.$.last_name":"New Lastname"          
    }
})`
and that:
`userService.update({
    "_id":"mainDocumentID",  
    "subdocs._id":"someId"
}, {
    $set:{
      "subdocs.$.last_name":"New Lastname"          
    }
})`
as supposed in this threads:
https://stackoverflow.com/questions/20262405/update-array-element-by-id-with-mongo-query
https://stackoverflow.com/questions/37612448/mongodb-positional-operator-error

What am i missing?

**Comment by daffl** [comment]
This should be doable by setting the `id` to `null` (to updated multiple records), the `query` to the query and using `patch`: 

```js
const query = { "_id":"mainDocumentID", "subdocs._id":"someId" }

userService.patch(null, { "subdocs.$.last_name":"New Lastname" }, { query });
```
