### ISSUE TITLE
Virtuals

### ISSUE THREAD

**Issue by Evanion** [feathersjs/feathers-mongoose#164]
Stack:
Latest feathers-cli (feathers-cli@1.2.7) generated app on node.js v7.4.0

When I add virtuals and toObject, toJson as per this section: https://github.com/feathersjs/feathers-mongoose/blob/25a034c3e398e84b131588dc1769a7b486111533/README.md#mongoose-schemas

I get `error: Route: /users - Maximum call stack size exceeded`

I'm trying to use a virtual to get the createdAt from the mongo ObjectId rather than storing it separately in the db.

**Comment by marshallswain** [comment]
https://steveridout.github.io/mongo-object-time/
This doesn't address the issue, but probably solves your use case.

**Comment by Evanion** [comment]
yea, it's the actual virtual functionality I want, I'm using the createdAt more as a test case.

**Comment by marshallswain** [comment]
From conversations I've had with others, you might want to avoid using Mongoose model instances and instead use lean queries and hooks for virtuals, if possible.  There's a huge performance reduction when using Mongoose and `toObject`.  It obviously won't matter if you're building a low-traffic API, but it's something that I'd want to be aware of if I were in your position and building a high-traffic API.  Once again, I'm not any help to fix the actual issue.  :)  I would just encourage finding another way of doing it if performance matters.

**Comment by daffl** [comment]
Is there some code we can use to reproduce the problem or can we close this issue?

**Comment by daffl** [comment]
Closing for now. Feel free to reopen if this has not been solved yet.
