### ISSUE TITLE
Please provide a working example for $push

### ISSUE THREAD

**Issue by idibidiart** [feathersjs/feathers-mongoose#165]
It seems that tests already exist for $push but given that it is not in the docs yet I assume it's under development.

Having said that, I have a pretty big array that I need to append to and I'm wondering if you point to a working example in the meantime, or give some idea as to when it will be ready for general consumption...?

Thanks

**Comment by daffl** [comment]
Please provide a breaking example where `$push` does not work as expected. This is not documented because it should work the same as in Mongoose.

**Comment by idibidiart** [comment]
```javascript
        createOrder(root, args, context){
          context.token = args.webtoken;
          let Orders = app.service('/orders');
          let Users = app.service('/users');
          let Items = app.service('/items');

          return new Promise(function(resolve, reject) {
              Items.find({
                query: 
                    {_id: 
                      {
                        $in: args.order.itemIds 
                      }
                    }
              }).then((items) => {
                  let total = `$${items.reduce((sum, item) => {
                                return sum + Number(item.itemPrice.slice(1))
                                }, 0)}`

                  args.order.total = total

                  Orders
                    .create(args.order, context)
                    .then((order) => {

                    // this should be all that is needed but $push is producing an error 
                    // filed an issue to see what's happening... 
                    //   
                    // Users
                    //   .update(order.userId, { $push: { orderIds: order.id } }, context)
                    //   .then(() => {
                    //     resolve(order)
                    //   })

                      var orderIds
                      Users.get(order.userId).then((user) => {
                        orderIds = user.orderIds   
                        Users
                          .patch(order.userId, { orderIds: orderIds.concat([order.id]) }, context)
                          .then(() => {
                            resolve(order)
                          })
                      })

                  }).catch((err) => reject(err))
                    
              })
          })
        }
```

User model has orderIds defined as:

```
  orderIds: { type: [String], 'default': []},
```

I get NO error. Simply, orderIds does not get populated using the commented out code. The twisted way I'm doing it now does work. Any insight, hint, idea as to what might be going on?

**Comment by idibidiart** [comment]
Maybe $push only works if the array is populated with at least one item? Hmm.

**Comment by daffl** [comment]
Here is a working example, in an empty folder run

> npm install feathers feathers-errors feathers-rest body-parser mongoose feathers-mongoose

Then create and `app.js` like this:

```
const feathers = require('feathers');
const errorHandler = require('feathers-errors/handler');
const rest = require('feathers-rest');
const bodyParser = require('body-parser');
const mongoose = require('mongoose');
const service = require('feathers-mongoose');
const Schema = mongoose.Schema;
const MessageSchema = new Schema({
  text: {
    type: String,
    required: true
  },
  items: [ { type: String } ]
});
const Model = mongoose.model('Message', MessageSchema);

// Tell mongoose to use native promises
// See http://mongoosejs.com/docs/promises.html
mongoose.Promise = global.Promise;

// Connect to your MongoDB instance(s)
mongoose.connect('mongodb://localhost:27017/feathers');

// Create a feathers instance.
const app = feathers()
  // Enable REST services
  .configure(rest())
  // Turn on JSON parser for REST services
  .use(bodyParser.json())
  // Turn on URL-encoded parser for REST services
  .use(bodyParser.urlencoded({extended: true}))
  // Connect to the db, create and register a Feathers service.
  .use('/messages', service({
    Model,
    lean: true, // set to false if you want Mongoose documents returned
    paginate: {
      default: 2,
      max: 4
    }
  }))
  .use(errorHandler());

// Start the server.
const port = 3030;
app.listen(port, () => {
    console.log(`Feathers server listening on port ${port}`);
});
```

At the end of `app.js`:

```js
// Create a dummy Message
app.service('messages').create({
  text: 'Message created on server',
  items: [ 'a' ]
}).then(function(message) {
  return app.service('messages').update(message._id, {
    $push: { items: 'b' }
  });
}).then(message => console.log('Created and pushed message', message));
```

As you can see, the item `'b'` gets added to the array as expected.

**Comment by idibidiart** [comment]
I feel terrible.

It was my fault in confusing .id with ._id so it was trying to push 'undefined' and Mongoose was barfing out some unintelligible error

'''if (castedDoc[keys[i]][_keys[ii]].$each) {
                                           ^
TypeError: Cannot read property '$each' of undefined'''

references line 38 of updateValidators.js in node_modules/mongoose/lib/services/

Thanks for your help. Anyway for Feathers-Mongoose to check for the item to be pushed to make sure it's defined or would that be like doing Mongoose' dirty work?

**Comment by daffl** [comment]
The [MongoDB $push documentation](https://docs.mongodb.com/manual/reference/operator/update/push/) says:

> If the field is absent in the document to update, $push adds the array field with the value as its element.

> If the field is not an array, the operation will fail.

So there should be no need to check unless it is set to not be an array.

**Comment by idibidiart** [comment]
The field is an array as you can see from the Mongoose model:

orderIds: { type: [String], 'default': []}

it's when the value to be pushed is undefined I get the error from Mongoose that I supplied above. 

It is not a Feathers issue, you're right about that but this is the second bug I found in Mongoose and I've only been playing with it for a short while.

**Comment by idibidiart** [comment]
@daffl i think you misunderstood or I was jot clear enough. It's not that the field is undefined when the error happens but the value itself (in your case 'b') is undefined. I will report the issue to Mongoose but the value existence check is what I was suggesting Feathers-Mongoose could do. Maybe not justified?

**Comment by nabaragpaul** [comment]
Will that push work with rethinkdb also?

**Comment by marshallswain** [comment]
@nabaragpaul No.  RethinkDB has a dramatically different syntax: https://stackoverflow.com/questions/22846614/how-to-append-an-element-to-an-array-in-rethinkdb  We have adapted a lot of the MongoDB query syntax to work with Feathers, but I'm pretty sure that $push is not included.  The RethinkDB syntax makes it difficult to create query syntax parity: https://stackoverflow.com/questions/22846614/how-to-append-an-element-to-an-array-in-rethinkdb

**Comment by ArjunAtlast** [comment]
When I Do a $push operation inside update my entire document content is gone:
**Content Before**
`{
      "_id": "60294d6dd89caf1e1e807588",
      "published": true,
      "scheduled": false,
      "title": "The Secret of the Nagas",
      "slug": "the-secret-of-the-nagas",
      "cover": {
        "square": "the-secret-of-the-nagas_square.png",
        "portrait": "the-secret-of-the-nagas_portrait.png",
        "landscape": "the-secret-of-the-nagas_landscape.png"
      },
      "createdAt": "2021-02-14T16:18:53.476Z",
      "updatedAt": "2021-02-20T08:17:37.060Z",
      "__v": 0,
      "deleted": false,
      "articles": []
    }`
**Query**
`await app.service("volumes").update("60294d6dd89caf1e1e807588", {
        $push: {
          "articles": "some id"
        }
});`
**Then**
`{
      "_id": "60294d6dd89caf1e1e807588",
      "createdAt": "2021-02-20T17:24:44.535Z",
      "updatedAt": "2021-02-20T17:24:44.535Z"
    }`
