### ISSUE TITLE
Should use underscores to donate filter params vs. params that are on a model

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-mongoose#17]

**Comment by marshallswain** [comment]
Why not just use **$** ?  It would be nice to "standardize" how this should work across services.  I'll be making a MySQL service sometime and think it would be nice to have similarities in the query/filter params.  Other than doing MySQL-specific operations like maybe `$join`, it would be nice for the API to match as much as possible.  I used `$` in [feathers-mongoose-advanced](https://github.com/marshallswain/feathers-mongoose-advanced#special-query-params) just to match what MongoDB is already using.

**Comment by ekryski** [comment]
Agreed. `$` it is. PR is coming that will close this and make it consistent between all adapters.

**Comment by daffl** [comment]
:+1:
