### ISSUE TITLE
virutal id plugin does not work anymore

### ISSUE THREAD

**Issue by uxtb** [feathersjs/feathers-mongoose#175]
### Steps to reproduce

I have virtualId plugin function:

    export const virtualId = schema => {
      schema.virtual('id').get(function(){
        return this._id.toHexString();
      });
      schema.set('toJSON', { virtuals: true });
      schema.set('toObject', { virtuals: true });
      return schema;
    };

In stable I was able to do:

    import mongoose from '../../mongoose';

    const projects = new mongoose.Schema({
      text: { type: String, required: true },
      createdAt: { type: Date, 'default': Date.now },
      updatedAt: { type: Date, 'default': Date.now }
    });

    projects.plugin(virtualId);

    const projectsModel = mongoose.model('projects', projects);

    module.exports = projectsModel;

Now when I do the same with Auk:

    module.exports = function(app) {
      const mongooseClient = app.get('mongooseClient');
      const { Schema } = mongooseClient;
      const projects = new Schema({
        text: { type: String, required: true },
        createdAt: { type: Date, default: Date.now },
        updatedAt: { type: Date, default: Date.now }
      });

      projects.plugin(virtualId);

      return mongooseClient.model('projects', projects);
    };

It does not work.

Both setups are based on generator defaults.

### Expected behavior
Plugin should be hooked and add `id` field in localhost:3030/projects

### Actual behavior
Plugin was ignored and no `id` field in localhost:3030/projects

### System configuration

Works with:

    "feathers": "^2.0.3",
    "feathers-mongoose": "^3.6.2",

Doesnt work with:

    "feathers": "^2.1.1",
    "feathers-mongoose": "^5.0.3",

**Comment by daffl** [comment]
`lean` is now `true` by default (that was the breaking change between 3.x and 4.x). If you want to use virtuals set `lean: false` in the options when intializing the service.

**Comment by uxtb** [comment]
@daffl thanks that was it!
