### ISSUE TITLE
Using [$in] with a single value

### ISSUE THREAD

**Issue by MasterCarl** [feathersjs/feathers-mongoose#185]
Currently, the correct way to query for a single value in array is `/users?roles=admin`, while the query for multiple values would be something like `/users?roles[$in]=admin&roles[$in]=moderator`.

Making a request `/users?roles[$in]=admin` returns an error `$in needs an array`.

When handling data from inputs like _multiple_ selects, this requires a distinction whether a single or multiple values are selected when making the API request. It would be useful if `/users?roles[$in]=admin` could just work.

**Comment by daffl** [comment]
You can coerce an array by using `/users?roles[$in][]=admin` or use a hook like this

```js
app.service('messages').hooks({
  before: {
    find(hook) {
      const { query = {} } = hook.params;

      Object.keys(query).forEach(key => {
        const value = query[key];

        if(value.$in && !Array.isArray(value.$in)) {
          value.$in = [ value.$in ];
        }
      });

      hook.params.query = query;

      return hook;
    }
  }
});
```

We are not doing any query parameter conversion since the handling of `$in` (and other values) depends on the adapter.
