### ISSUE TITLE
Mongoose dependency issues

### ISSUE THREAD

**Issue by cfitton** [feathersjs/feathers-mongoose#193]
### Steps to reproduce
N/A

### Expected behavior
Mongoose should be listed as a peer dependency to allow developers to change the version of Mongoose.

### Actual behavior
Mongoose is listed as a dev dependency.

If the installed versions differ in the app, e.g. feathers-mongoose has 4.5.2 and the app has 4.9.7, then the behaviour in development and production will differ.

**Comment by marshallswain** [comment]
Aren't devDependencies only installed when you run `npm install` in the root of the `feathers-mongoose` package, though?

**Comment by daffl** [comment]
`peerDependencies` are [not supported by newer versions of npm anymore](http://blog.npmjs.org/post/110924823920/npm-weekly-5). You can install and use any version of Mongoose that is supported (our tests automatically run against the latest kept up to date by Greenkeeper).
