### ISSUE TITLE
Mongoose middleware not working correctly with feathers?

### ISSUE THREAD

**Issue by adetwiler** [feathersjs/feathers-mongoose#196]
Hello,

I'm brand new to feathers and when I tried this using just express and it worked, however when doing this using feathers, I'm getting undefined when trying to access `this` within the scope of a mongoose middleware.

```
userSchema.pre('save', (next) => {
  const user = this;
  const saltRounds = 5;

  if (!user.isModified('password')) return next();

  bcrypt.genSalt(saltRounds, (err, salt) => {
    if (err) return next(err);
    bcrypt.hash(user.password, salt, null, (bcryptErr, hash) => {
      if (bcryptErr) return next(bcryptErr);
      user.password = hash;
      next();
    });
  });
});
```

`const user = this` is undefined. I'm not sure if there is another way I'm supposed to be doing this or if this is an issue with the feathers-mongoose connector in some way?

**Comment by daffl** [comment]
Welcome! Are you sure that worked before? If you use an arrow function (`(next) => {}`) the context is probably wrong (it will be the parent scope and `unedfined` if you run this at the top level of your JavaScript file). It will probably work using a normal JavaScript function (where the context can be set dynamically) like

```js
userSchema.pre('save', function(next) => {
  const user = this;
  const saltRounds = 5;

  if (!user.isModified('password')) return next();

  bcrypt.genSalt(saltRounds, (err, salt) => {
    if (err) return next(err);
    bcrypt.hash(user.password, salt, null, (bcryptErr, hash) => {
      if (bcryptErr) return next(bcryptErr);
      user.password = hash;
      next();
    });
  });
});
```

**Comment by adetwiler** [comment]
@daffl Thanks for your reply. I see what I did wrong, I am also new to es6 and did not realize arrow functions took away the `this` context. Thanks for your help!
