### ISSUE TITLE
Support batch creates

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-mongoose#21]

**Comment by marshallswain** [comment]
We need batch support for
 - [x] create -  already working.
 - [ ] update
 - [ ] patch
 - [ ] delete

**Comment by ekryski** [comment]
Might be time to revisit this now that we have https://github.com/feathersjs/feathers-batch and some of the changes to core that support this functionality landed.

batch updates won't happen but `patch` and `delete` will.

**Comment by daffl** [comment]
feathers-batch shouldn't be necessary to create multiple resources. In the new adapters everything that's usually necessary is

```js
create: function(data, params) {
  if(Array.isArray(data)) {
    return Promise.all(data.map(current => this.create(current, params)));
  }
}
```

**Comment by daffl** [comment]
delete and patch many also is a little different to batching requests. Something like `DELETE /todos?complete=true` which would delete all completed todos wasn't possible before Feather 1.3.

**Comment by ekryski** [comment]
ok, then we can add that functionality when we convert it over to ES6. Probably later today but I gotta get some :sleeping:

**Comment by daffl** [comment]
This should be fixed now, too.

**Comment by idibidiart** [comment]
I just had a related conversation with @daffl on Slack 

Just to make sure, do patch and delete support a *single* write that mutate many parts of a given document? (i.e. across many id's) According to Mongo docs, single writes that mutate multiple subdocuments within a single document (on a single mongod instance) are atomic.

**Comment by daffl** [comment]
Yes it does. See at https://github.com/feathersjs/feathers-mongoose/blob/master/src/service.js#L264 and https://github.com/feathersjs/feathers-mongoose/blob/master/src/service.js#L288 where it uses `Model.update` and `Model.remove` to update multiple models based on the query.

**Comment by idibidiart** [comment]
Awesome. Thank you. 

So why doesn't this extend to create and update? I don't have a use case for atomic creates and updates but I'm curious about their exclusion.

**Comment by daffl** [comment]
It does extend to `create` (just pass an array for the `data`).

`update` doesn't make much  sense for multiple records. It is very unlikely that you want to completely replace a whole set of resources.

**Comment by idibidiart** [comment]
That's true. Absolutely awesome! Thank you for thinking of all these things ahead of time! :)
