### ISSUE TITLE
Mongoose query aggregation

### ISSUE THREAD

**Issue by Aranad** [feathersjs/feathers-mongoose#212]
Is there any way to use the Mongo/Mongoose [collection aggregation-pipline](https://docs.mongodb.com/master/reference/operator/aggregation-pipeline/) from feathers-mongoose?

**Comment by jamesjnadeau** [comment]
I don't think there is, as it strays too far from the "unified query system"(or whatever it's called, please correct me), 

You could extend/override the find/_find functions to customize this to your will though.

**Comment by corymsmith** [comment]
@Aranad I've created custom services that use aggregation underneath. Or if you need an aggregation in addition to other data from a service you could add an after hook that does the aggregation as well.

**Comment by Aranad** [comment]
@corymsmith that sounds awesome... could you point me in the right direction to read up on and implement that, thanks! :-)

**Comment by zusamann** [comment]
maybe try putting the params in params.mongoose

**Comment by corymsmith** [comment]
@Aranad Theres some info here on creating a custom service, unfortunately my custom service is proprietary so I can't share it: https://docs.feathersjs.com/api/services.html

**Comment by Aranad** [comment]
I figured out a way to do it from the before.find hook. hook.service.Model is the mongoose model object that has aggregate() available, so I made a convention for passing aggregate data in find() which the hook can detect and divert to the aggregate method :-)

**Comment by corymsmith** [comment]
Perfect!

**Comment by daffl** [comment]
Glad it worked! Closing this one then.

**Comment by stalinb87** [comment]
@Aranad how exactly do you accomplish this, do you have some example?

**Comment by Aranad** [comment]
@stalinb87 yes I documented how I did it here: https://www.organicdesign.co.nz/Our_SPA#Database_schemas_and_querying, a similar method could also be done with the hook added on the server side instead to avoid complex query descriptions needing to be sent from the client to the server.

**Comment by MacgyverMartins** [comment]
You can override `context.params.query` at `before.find` hook whit the mongoose query

**Comment by priyabagus** [comment]
Example aggregate for `users`

```
await app.service('users').Model.aggregate( [ { <stage1> }, { <stage2> } ... ] )
```
