### ISSUE TITLE
Can not call update with a null id

### ISSUE THREAD

**Issue by apparentvisuals** [feathersjs/feathers-mongoose#214]
### Steps to reproduce

The services section of Feathers documentations states: 

> update(id, data, params) -> Promise - replaces the resource identified by id with data. The method should return a Promise with the complete updated resource data. id can also be null when updating multiple records with params.query containing the query criteria.

However, when using feathers-mongoose and calling update(null, data, param) throws 

> 'Not replacing multiple records. Did you mean `patch`?' exception

### Expected behavior
Update call should succeed

### Actual behavior
Update call fails with BadRequest

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
feathers-mongoose@5.1.2

**NodeJS version**:
8.5.0

**Operating System**:
Ubuntu 16.04

**Comment by daffl** [comment]
This is by design since there isn't a lot of cases where you want to blow away an entire set of data and replace it with the same data. This is also [documented in the database adapter specific API](https://docs.feathersjs.com/api/databases/common.html#adapterupdateid-data-params---promise):

> Does not allow replacing multiple records (id can't be null).
