### ISSUE TITLE
 Find Query with $in array of ObjectId's 

### ISSUE THREAD

**Issue by neerajincaendo** [feathersjs/feathers-mongoose#216]
hook.app.service('books').find({query: {$in:{members:[userId]}} ) 

its giving 0 results , userId is Mongoid in schema , do i need to cast userId into ObjectId or something else is the problem , what's the solution , ASAP

**Comment by daffl** [comment]
As pointed out in Slack, the query should be

```js
hook.app.service('books').find({
  query: {
    members: { $in: [ userId ] }
  }
});
```
