### ISSUE TITLE
Document using virtuals.

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-mongoose#23]
Setting up a virtual currently does nothing to the output  This is currently enabled separately in Mongoose using the following commands:

```js
// Create a virtual field for id.
schema.virtual('id').get(function(){
    return this._id.toHexString();
});
// Ensure virtual fields are serialised.
schema.set('toJSON', {virtuals: true});
schema.set('toObject', {virtuals: true});
```

**Comment by ekryski** [comment]
@marshallswain Again, I think this is more of a documentation issue. If you are working with the mongoose model inside a hook you do have access to the virtuals. If you want virtuals included in your output I think you should have to specify that explicitly like you did above. That's really part of mongoose.

**Comment by ekryski** [comment]
@marshallswain thanks mate!

**Comment by germanp** [comment]
Hi,

The documentation about mongoose's virtuals is not more abailable. What is the suggested way to work virtuals?

I've found that specfiyng lean = false and doing the aforementioned it makes this to work

**Comment by loonfly** [comment]
seem like 
`// Create a virtual field for id.
schema.virtual('id').get(function(){
    return this._id.toHexString();
});
// Ensure virtual fields are serialised.
schema.set('toJSON', {virtuals: true});
schema.set('toObject', {virtuals: true});`

still doesn't work. the output contain no id, only _id. any other options i need to set beforehand?

**Comment by loonfly** [comment]
// Create a virtual field for id.
  schema.virtual("id").get(function() {
    return this._id.toHexString();
  });

  schema.set("toJSON", { virtuals: true });
  schema.set("toObject", { virtuals: true });

front end is ReactJS with Redux

With this setup, I realize when i service().create() from client to server, the id is in the response. but when service().find() the id is not there, only _id

I did most things accordingly, curious what's wrong or am i missing out anything?

**Comment by EmitoSanti** [comment]
> // Create a virtual field for id. schema.virtual("id").get(function() { return this._id.toHexString(); });
> 
> schema.set("toJSON", { virtuals: true }); schema.set("toObject", { virtuals: true });
> 
> front end is ReactJS with Redux
> 
> With this setup, I realize when i service().create() from client to server, the id is in the response. but when service().find() the id is not there, only _id
> 
> I did most things accordingly, curious what's wrong or am i missing out anything?

Solution ->>>

The problem is the "lean" option in mongoose queries. Feathers.JS has lean = "true" as default (this can be easily seen in the "feathers-mongoose" codebase). More info: https://mongoosejs.com/docs/6.x/docs/api/query.html#query_Query-lean.

solutions:
use a plugin or
in the .service.js of your service set the option -> lean: false in the object
