### ISSUE TITLE
Utilize query.lean() to get plain objects.

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-mongoose#24]
We need to call query.lean() before execution to save resources. It's the same result as .toJSON, but it makes the query just return the JSON so there's no converting necessary.  If we need the Mongoose model objects, we can convert later.

**Comment by ekryski** [comment]
Rather than repeat myself. See my response in https://github.com/feathersjs/feathers-hooks/issues/23

**Comment by marshallswain** [comment]
Related to #25.  Closing.
