### ISSUE TITLE
Add documentation for use with feathers-hooks

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-mongoose#25]
As came up in the issue at https://github.com/feathersjs/feathers-hooks/issues/23, modifying the Mongoose models this adapter returns in a hook can cause some unexpected behaviour. We probably want to add some documentation and with Feathers 2.0 some hooks in this repository that help dealing with this.

**Comment by marshallswain** [comment]
Here's what I think this needs:
 - [ ] A configurable `toObject` hook.
 - [ ] Docs.

http://mongoosejs.com/docs/api.html#document_Document-toObject

**Comment by ekryski** [comment]
Agreed. We also might see some nice patterns emerge with some of the other ORM adapters coming out soon.

**Comment by ekryski** [comment]
This was closed with PR #33.
