### ISSUE TITLE
NPM Release for feathers-hooks

### ISSUE THREAD

**Issue by mickmcgrath13** [feathersjs/feathers-mongoose#29]
I would like to use the feathers-hooks functionality.  Can this be deployed to NPM?

@marshallswain

**Comment by marshallswain** [comment]
Today's the day.  I have one more thing to finish on it, then I'll publish.

**Comment by mickmcgrath13** [comment]
On It!  Thanks!

**Comment by ekryski** [comment]
What's the dealio? feathers-hooks should be published to npm. It's been out for a few months now.

Or is the problem that feathers-mongoose isn't playing nice? @marshallswain

**Comment by daffl** [comment]
It's for adding Hooks in the schema (https://github.com/feathersjs/feathers-mongoose#using-with-feathers-hooks). We probably want to release this soon since it is in the docs already.

**Comment by marshallswain** [comment]
Sorry, I got pulled back to client work before finishing.  I only have to add the tests and it's done.  Working on this now.

**Comment by jamesjnadeau** [comment]
@marshallswain please update this when you post, thanks so much!

(ps just realized that the docs don't match up with what I was getting from npm, whoops, glad this issue was here, I was about to move to something else for the day....)

**Comment by marshallswain** [comment]
Sure thing.

**Comment by jamesjnadeau** [comment]
@marshallswain This issue should not have been closed. 

The version of feathers-mongoose currently on npm does not match up with master, and does not contain the code required to integrate with feathers-hooks.

You probably didn't mean to have this happen, but just letting you know that this is still an issue, and that this is going to confuse new developers until this is fixed. 

I'm working around this by requiring the package from git at the specific commit that adds this feature:

```
npm install --save https://github.com/feathersjs/feathers-mongoose.git#4dc4d5d
```

Not ideal, but hope this helps anyone in the future encountering these troubles.

**Comment by ekryski** [comment]
I think the version on npm should have support for feathers-hooks. We will however have a brand new release today as well. There are some minor breaking changes but docs, hooks, examples will all be up to date and consistent with the other adapters.

Just give me until the end of the day today. Shouldn't take me long but I'm dealing with kids at the moment.

**Comment by ekryski** [comment]
Ah :hankey:! Looking at it the version didn't get bumped. Probably because I said I was going to have the new version out a week ago. My bad. Just give me until the end of today @jamesjnadeau, I'll try and get this stuff in really quick.

**Comment by jamesjnadeau** [comment]
Honestly, no big deal, don't rush it, no need to apologize, just wanted to make the powers at be aware :) 

Keep those kids asleep for as long as you can!
