### ISSUE TITLE
Documentation on troubleshooting

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-mongoose#31]
So, I just had a really dumb moment.  I couldn't figure out whey a simple query like `find({accountNumber: 12345})` wasn't returning any data when it was clearly in the database correctly.  I finally figured out that I had failed to add the `accountNumber` field to the Mongoose schema (duh), which was preventing it from making it into the query.  It might be nice for newcomers or for those having short- or long-term stupid moments to have a blurb on this in the docs.  Maybe a troubleshooting section where we could add these little potential gotchas whenever encountered.  I think this would help newcomers to not blame feathers or the adapter and jump ship.

**Comment by daffl** [comment]
That's a good idea. Could this also be caught as an error (if there is a field in the query that's not in the schema)?

**Comment by ekryski** [comment]
That's what I was thinking. Throw a warning instead of having it in the docs. Worth spiking out but it might be too complex to assess that. We'll have to see...

**Comment by ekryski** [comment]
I think in this instance it's an honest mistake and you'd see the exact same thing with mongoose. If it comes again or you feel like documenting it @marshallswain feel free to re-open and have at it! Otherwise I think all the additions we have made to the docs have most things covered.
