### ISSUE TITLE
Add docs for overriding the service methods (patch for example)

### ISSUE THREAD

**Issue by jamesjnadeau** [feathersjs/feathers-mongoose#34]
The current patch method just calls the update function, perfectly fine default functionality IMHO. However, I'm more used to the patch operation just updating the fields it's sent, not the whole record, so when I started out with feathers-mongoose, I sought a way to override this method to do what I want.

Overriding this functionality would be a good teaching moment for the docs to show how this is done. Took me a while to hunt down the preferred way to do it via a issue from someone else posted(https://github.com/feathersjs/feathers-mongoose/issues/26).

It would be nice to move this useful info to the readme. Altering methods, and even adding their own, is high up on the list of first things a developer is going to want to do when they start using feathers-mongoose. Getting info on the best way to do it out there early so people can hit the ground running is going to improve the experience of first time users.

Also on a related note, @ekryski, how would you recommend/envision extending/overriding a service method with es6 code base you are working on in https://github.com/feathersjs/feathers-mongoose/pull/33? Might want to throw docs on that into your work in progress. Thanks so much for your time in advance! Keep up the great work!

**Comment by ekryski** [comment]
@jamesjnadeau thanks for the notes mate! Ya I think the biggest issue here is that we are rolling out the new ES6 stuff and there are still some docs to get updated. Will have that done and that PR merged today.

Extending is going to be the same as all the other adapters so you could take a look at [feathers-sequelize extending](https://github.com/feathersjs/feathers-sequelize#extending) to see how it is going to work.

**Comment by jamesjnadeau** [comment]
Maybe a common doc that has tips and tricks of using feathers that other readmes can point too? Perhaps another repo under feathersjs for these universal docs?
(thinking out-loud here, feel free to ignore me :) )

**Comment by ekryski** [comment]
@jamesjnadeau We have plans to update the main website and docs shortly (https://github.com/feathersjs/feathers/issues/184).

Not sure if you have seen those at all. They're just not as organized but we wanted to get some of our other changes in place before we update the docs, because we have quite of few changes coming to close pretty soon here (https://github.com/feathersjs/feathers/milestones/2.0.0).

**Comment by jamesjnadeau** [comment]
I have seen none of it, thanks for pointing me in the right direction! 
Thanks so much, you've been extremely helpful.

**Comment by jamesjnadeau** [comment]
I'm going to close this as I think this will be covered in other updates.
