### ISSUE TITLE
With toObject(), ObjectIDs aren't stringified.

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-mongoose#43]
This might be a documentation fix or potentially a code update to check if `id` is an ObjectID and stringify it here: https://github.com/feathersjs/feathers-mongoose/blob/master/src/service.js#L90

**Comment by marshallswain** [comment]
This is only an issue with inter-service communication, internally.

**Comment by ekryski** [comment]
@marshallswain is this still an issue? I've never run into this issue with the latest version, although I remember in the feathers-mongoose < 3 having to do some ObjectId casting.

**Comment by marshallswain** [comment]
I don't think it is.  Let's close it.  I can always reopen if needed.
