### ISSUE TITLE
Support $search

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-mongoose#50]
This is a proposed special attribute that allows you to fuzzy match a property. Possibly even multiple properties and/or nested documents.

Suggested syntax:

```js
name: {
  $search: ['alice', 'Alice', 'bo', /$bob/i]
}
```

Following similar syntax to our other special query filters, this would allow you to filter by a singular value, multiple values (treated like an **or**) and/or regular expressions directly.

Internally mongoose requires a $regex query but we can fairly easily build a singular regex from this array.

**Comment by marshallswain** [comment]
Mongoose syntax that works: `query = { fieldName: { $regex: 'pattern', $options: 'igm' } }`

**Comment by jamesjnadeau** [comment]
I think this might best be applied as a example hook in the docs, here's what I used:

```js
function $search(hook) {
  if (hook.params.query.$search) {
    var search = hook.params.query.$search;
    var regEx = new RegExp('.*' + search + '.*', 'i');
    delete hook.params.query.$search;
    hook.params.query.$or = [
      { name: regEx },
      { email: regEx },
      { address1: regEx },
      { address2: regEx },
    ];
  }
}

service.before = {
  find: $search,
}
```

Shows off two things that I think are important to highlight in the gitbook for hooks:
1. How to create your own query param and access it
2. How to overwrite the query being used later on in the adapter.

IMHO having a generalized approach to this in the adapter is not what people need to be doing. You should be customizing this to your apps needs. Having rich examples of usage in the docs helps people get there.

**Comment by daffl** [comment]
See https://github.com/feathersjs/feathers/issues/334

**Comment by ForsakenHarmony** [comment]
this got removed again?
