### ISSUE TITLE
$populate options does not work in get() queries

### ISSUE THREAD

**Issue by BigAB** [feathersjs/feathers-mongoose#53]
For example:

`/api/people?$populate[]=pets` [find] populates the pet property just fine, 

But:

`/api/people/david-brown?$populate[]=pets` [get] will **not** populate the pets property

**Comment by ekryski** [comment]
:boom: @marshallswain beat me to it! Nice PR @BigAB. Thanks!

**Comment by Mentioum** [comment]
This was godly @BigAB :)
