### ISSUE TITLE
Add a way to $push in a PATCH

### ISSUE THREAD

**Issue by harangue** [feathersjs/feathers-mongoose#68]
I think it makes sense to be able to patch in an array item, using mongo's `$push` operator.

**Comment by beeplin** [comment]
alternatively you can just use `service.update(id, {$set: {...}})` instead of `service.patch(id, {...})`, and then `$push` is available in `update`.

**Comment by harangue** [comment]
Just to follow up on this, using `update` makes `$push` work perfectly fine. It might be able to stay that way, but semantically it seems like it would be appropriate for it to work under a `patch`. Plus when you use `update` with the intent to only mutate it means extremely careful validation of the data coming in with the update. Thoughts?

**Comment by ekryski** [comment]
I think `patch` should support it as well. It's definitely slated to make it's way in.

**Comment by imns** [comment]
I would also like to see this implemented.

**Comment by ekryski** [comment]
I'm working on this right now but you can also use the ORM methods to do push updates onto arrays. http://mongoosejs.com/docs/subdocs.html

**Comment by ekryski** [comment]
Released as v3.4.1
