### ISSUE TITLE
custom query

### ISSUE THREAD

**Issue by robotnic** [feathersjs/feathers-mongoose#69]
I have this query
```
db.votes.aggregate([{ $group: { _id: "$report",votings:{ $push: {id:"$voteid",for:"$For.total",against:"$Against.total",abstain:"$Abstain.total"} },title:{$first:"$eptitle"} }},{$skip:50},{$limit:50} ])
```
It should return the a REST list. 
Where do I put this query?

Is it possible to use a hook for this?
Should I use the express router?

**Comment by ekryski** [comment]
@robotnic yes you can use it in a hook. You have a few options. My suggestion would be to use the [mongoose aggregate](http://mongoosejs.com/docs/api.html#index_Mongoose-Aggregate) feature. Then in your hook you can just do:

```js
function(options = {}) {
  return function(hook) {
    let Model = hook.app.service('votes').Model;
    const conditions = [{
      $group: {
        _id: "$report",
        votings: {
          $push: {
            id:"$voteid",
            for:"$For.total",
            against:"$Against.total",
            abstain:"$Abstain.total"
          }
        },
        title: { $first: "$eptitle" }
      }
    },{
      $skip:50
    },{
      $limit:50
    }];

    return new Promise(function(resolve, reject){
      Model.aggregate(conditions).exec(function(error, result){
        if (error) {
          return rejct(error);
        }

        // Do whatever
        resolve(result);
      });
    });
  };
}
```

Something to that effect. I forget the aggregate syntax for mongoose. Another option is you can have a middleware where you expose the db object to all of your services:

```js
app.use(function(req, res, next) {
  // Get your db object from somewhere and expose
  // it to services and hooks.
  req.feathers.db = db;
})
```

Either way, you should be able to get the db object somehow in your hook and a hook is the right place to put this. Let me know if that doesn't help and we can re-open this issue.
