### ISSUE TITLE
$select doesn't work in find?

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers-mongoose#71]
$select doesn't work in find operation. I found that the source code for $select is not the same as that in other packages like `feathers-mongodb` or `feathers-nedb`. Normally the code would be like this:
```
    // $select uses a specific find syntax, so it has to come first.
    if (filters.$select) {
      query = this.Model.find(params.query, getSelect(filters.$select));
    }
```
but in `feathers-mongoose` (via github) it is like:
```
    // $select uses a specific find syntax, so it has to come first.
    if (filters.$select && filters.$select.length) {
      let fields = {};

      for (let key of filters.$select) {
        fields[key] = 1;
      }

      query.select(fields);
    }
```
and furthermore, in the actually `feathers-mongoose` npm package (v3.3.6) the source code is:
```
      // $select uses a specific find syntax, so it has to come first.
      if (filters.$select && filters.$select.length) {
        var fields = {};

        var _iteratorNormalCompletion = true;
        var _didIteratorError = false;
        var _iteratorError = undefined;

        try {
          for (var _iterator = filters.$select[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
            var key = _step.value;

            fields[key] = 1;
          }
        } catch (err) {
          _didIteratorError = true;
          _iteratorError = err;
        } finally {
          try {
            if (!_iteratorNormalCompletion && _iterator.return) {
              _iterator.return();
            }
          } finally {
            if (_didIteratorError) {
              throw _iteratorError;
            }
          }
        }

        query.select(fields);
      }
```

**Comment by ekryski** [comment]
@beeplin how are you passing it to your code. We have tests that cover this that are passing.

**Comment by beeplin** [comment]
I just cloned `feathers-chat` project, changed it's service from nedb to mongoose, and modify `/public/react-chat/app.jsx` L128 to:
```
    // Find the last 10 messages
    messageService.find({
      query: {
        $select: {
          _id: 0,
          'text': 0
        },
        $sort: { createdAt: -1 },
        $limit: this.props.limit || 10
      }
    }).then(page => this.setState({ messages: page.data.reverse() }));
```
other stuffs work perfectly including $sort, &skit and #limit, but $select seems to be ignored.

**Comment by ekryski** [comment]
Hmm. ok we'll have to look into it. Unfortunately, it won't happen today.

**Comment by beeplin** [comment]
take ur time. :) if this got solved I d like to transform my old project from mongodb to mongoose and enjoy feathers~~

**Comment by jamesjnadeau** [comment]
I'm not sure if others have noticed this, and it has to do with query parsing in your client, but I found that depending on how your request handler parses the query, and creates the subsequent url, you might have issues that are hard to debug without digging deeper.

@beeplin can you please try the following and see if you get what you are looking for:
```
// Find the last 10 messages
    messageService.find({
      query: {
        '$select[_id]': 0,
        '$select[text]': 0,
        $sort: { createdAt: -1 },
        $limit: this.props.limit || 10
      }
    }).then(page => this.setState({ messages: page.data.reverse() }));
```

you're probably going to have to do the same to the $sort variable, or pass it in via text like:
```
$sort: '-createdAt'
```

**Comment by daffl** [comment]
I think the docs are wrong. The [service tests](https://github.com/feathersjs/feathers-service-tests/blob/master/src/common-tests.js#L170) use an array. Can you try

```js
    messageService.find({
      query: {
        $select: ['_id', 'text' ],
        $sort: { createdAt: -1 },
        $limit: this.props.limit || 10
      }
    }).then(page => this.setState({ messages: page.data.reverse() }));
```

**Comment by daffl** [comment]
If that is the case, removing fields can probably be done best using the [remove hook](http://docs.feathersjs.com/hooks/bundled.html#remove) instead.

**Comment by daffl** [comment]
This was indeed a mistake in the documentation, sorry about that. It is fixed now and works as I described above.

**Comment by beeplin** [comment]
so this array syntax only works for mongoose or for all other db adapters too?

**Comment by marshallswain** [comment]
@beeplin This is part of our shared tests for all adapters: https://github.com/feathersjs/feathers-service-tests/blob/master/src/common-tests.js#L166

So all of them should support it.

**Comment by beeplin** [comment]
got it. Thanks~


来自 魅族 MX5

-------- 原始邮件 --------
发件人：Marshall Thompson <notifications@github.com>
时间：周三 3月23日 16:10
收件人：feathersjs/feathers-mongoose <feathers-mongoose@noreply.github.com>
抄送：Beep LIN <beeplin@gmail.com>
主题：Re: [feathers-mongoose] $select doesn't work in find? (#71)

>@beeplin This is part of our shared tests for all adapters: https://github.com/feathersjs/feathers-service-tests/blob/master/src/common-tests.js#L166 So all of them should support it. —You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub
