### ISSUE TITLE
Bypass of methods

### ISSUE THREAD

**Issue by quick691fr** [feathersjs/feathers-mongoose#76]
It should be good to get an option to bypass easily some methods, I'm thinking of a soft delete of documents by putting a boolean flag deleted : true instead of remove the document.

**Comment by daffl** [comment]
This is already possible by setting `hook.result` in a [before hook](http://docs.feathersjs.com/hooks/usage.html#before-hooks). A soft delete can be done like this:

```js
app.service('messages').before({
  find(hook) {
    hook.params.query.deleted = { $ne: true };
  },

  remove(hook) {
    return this.patch(hook.id, { deleted: true }, hook.params).then(message => {
      hook.result = message;
      return hook;
    });
  }
});
```

**Comment by quick691fr** [comment]
Thanks
