### ISSUE TITLE
hooks.toObject() fails if data is paginated

### ISSUE THREAD

**Issue by harangue** [feathersjs/feathers-mongoose#77]
The hook only works for mongoose resources on `result`, not `result.data`. I'll probably submit a PR shortly.

**Comment by jamesjnadeau** [comment]
This adapter uses the mongoose .lean() functionality when fetching multiple resutls, that makes using .toObject() not necessary in this case. However, you could configure it to not use lean.

Please take a look at this discussion: https://github.com/feathersjs/feathers-mongoose/issues/51

**Comment by harangue** [comment]
@jamesjnadeau It defaults to false, and I'd rather not have it apply service-wide. Either way I think the hook should be fixed.

**Comment by jamesjnadeau** [comment]
My mistake then, in my head(and my projects), lean is true by default....

**Comment by ekryski** [comment]
@harangue yup this is totally valid. Thanks for bringing it up and tackling it Jack!
