### ISSUE TITLE
Cast to ObjectId failed for value X at path "_id"

### ISSUE THREAD

**Issue by 29er** [feathersjs/feathers-mongoose#81]
I'm pretty sure it's something  silly that's causing these issues, because I'm just starting to try out Feathers, but I cannot update a record in my mongoose/mongodb due to this error.

Here is my model 
```
import mongoose from 'mongoose';
const Schema = mongoose.Schema;

export default mongoose.model('post',
  new Schema({
    uuid : { type: String, required: true, unique: true },
    title: { type: String, required: true },
    createdAt: { type: Date, default: Date.now },
  }));

```
The CREATE works fine ie: 
service('myService').create(jsonObj);

but I get errors when I do an UPDATE:

```
update(item) {
    return service('myService')
    .update(item.uuid, { title: item.title }, (resp) => {
      //errors
    });
  }
```

the response object is 'BadRequest" and message is "Cast to ObjectId failed for value "bf35271d-c5b9-4445-98ac-ccbd9e378a57" at path "_id""

Can anyone help out this newbie ?

**Comment by daffl** [comment]
It looks like you want to use `uuid` as the id property. Did you set the `id` [option when initializing](http://docs.feathersjs.com/databases/mongoose.html#options) the service?

**Comment by 29er** [comment]
@daffl - thank you!  I overlooked that . much appreciated.

**Comment by daffl** [comment]
It could've been totally valid. There were some sneaky bugs when using custom ids so definitely file another issue if you notice anything weird.

**Comment by kaankocturk** [comment]
Hey guys. I have a similar error I can't figure out for 3 days now. Can you please help?
Here it is: http://stackoverflow.com/questions/41568481/cast-error-when-using-populate-works-on-localhost-but-error-on-heroku-mongolab?noredirect=1#comment70419349_41568481
thank you!
