### ISSUE TITLE
Embedded documents validation using model validation

### ISSUE THREAD

**Issue by quentin-sommer** [feathersjs/feathers-mongoose#88]
Hi,

using mongoose model validation on embedded documents the error printed is in form of `[object Object]` (I guess because it's a nested error object for the sub-doc ?), How could I make sure it gets entirely serialized ?

``` javascript
// main document schema
const userSchema = new Schema({
  email: {
    type: String,
    required: true
  },
  password: {
    type: String,
    required: true
  },
  subDoc: [sub]
});

// sub document schema
const subDoc = new Schema({
  username: {
    type: String,
  }
});
```

**Comment by daffl** [comment]
I just verified that it sends the entire error. If you are just `console.log`ing the error you might want to try `console.log(JSON.stringify(error.toJSON()))`.
