### ISSUE TITLE
Is this possible for multiple insert using Feathers mongoose?

### ISSUE THREAD

**Issue by RaghavendhraK** [feathersjs/feathers-mongoose#94]
Hi,
Could you please provide how we can have array of records to be inserted using feathers mongoose.
Thanks,
Raghu

**Comment by daffl** [comment]
You pass an array as the `data` to `create`. The test for it is at https://github.com/feathersjs/feathers-service-tests/blob/master/src/common-tests.js#L473

**Comment by RaghavendhraK** [comment]
Thanks for the quick reply :+1:
