### ISSUE TITLE
Update README.md to reflect change to 'name' option for the service.

### ISSUE THREAD

**Issue by githugger** [feathersjs/feathers-mongoose#96]
The [readme](https://github.com/feathersjs/feathers-mongoose/blob/master/README.md) displays the use of a mongoose-service option *"name"* in the code example "Complete Example". The option and corresponding service property appear to have been deprecated with 210ccc882ce439ee34d559f70fb2bc69ec6173ba:

**Excerpt from Complete Example in the readme:**
```javascript
// Connect to the db, create and register a Feathers service.
app.use('messages', service({
  name: 'message',
  Model: Message,
  paginate: {
    default: 2,
    max: 4
  }
}));
```

**Excerpt from [service.js](https://github.com/feathersjs/feathers-mongoose/blob/master/src/service.js):**
```javascript
// this.name = options.name;
this.Model = options.Model;
this.id = options.id || '_id';
this.paginate = options.paginate || {};
this.lean = options.lean || false;
this.overwrite = (options.overwrite === false) ? false : true;
```

I don't know what this option or the corresponding service property have originally been used for, but to me it seems they are not in use anymore, so I suggest changing the line of the readme. If I am not misreading the service.js and it is not the intention to add back the option in an upcoming release I can create a pull request.

*Edit:* Okay I just created a PR for this, because the name option does not seem to do anything in the current release.

**Comment by daffl** [comment]
Closed via https://github.com/feathersjs/feathers-mongoose/pull/97
