### ISSUE TITLE
We shouldn't remove properties from original objects

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-mongoose#98]
Originally this came up in [the NeDB adapter](https://github.com/feathersjs/feathers-nedb/issues/29). But we should not be [calling `delete`](https://github.com/feathersjs/feathers-mongoose/blob/master/src/service.js#L179) on the original object. Instead we should make a copy and then call delete, or only pluck the keys that we want.

**Comment by daffl** [comment]
Closed via #100
